#!/usr/bin/python3.9

import json

banner = """
     //////  ///////  //
     //  //  //   //  //
     //////  ///////  //
     //  //  //       //
     //  //  //       //  MAKER
     
  TTTTTTTTT OOOOOOO OOOOOOO LL
     TT     OO   OO OO\033[32;1mOOO\033[00;0mOO LL
     TT     OO   OO OO\033[32;1mOOO\033[00;0mOO LL
     TT     OO   OO OO\033[32;1mOOO\033[00;0mOO LL
     TT     OOOOOOO OOOOOOO LLLLLLL
     
     [=] Development by D45H7
     [=] by EtcAug10
 
"""

def postData(x):
  print("Data yang kamu masukkan:\n")
  print("STRING:\n",x)
  print("\nJSON ENCODED:\n",json.loads(str('{'+x+'}')))
  apiName = input('\nYour API\'s name: ')
  phpcode = """
<?php 
error_reporting(0);
$data = array("""+x.replace(':','=>')+""");
?>
<!DOCTYPE HTML>
<html>
  <head>
    <title>Api</title>
    <meta name="robots" content="noindex,nofollow">
    <meta name="description" content="MyAPI Tool Generated by D45H7">
  </head>
  <body>
    <?php
      if(isset($_GET['q'])) {
        echo json_encode($data);
      }
      else {
        echo "Input query first";
      }
    ?>
  </body>
</html>
"""
  open(apiName+".php","a").write(phpcode)
  print("Your data was generated in "+apiName+".php file")

def main():
  data = '"status":"[GANTI SENDIRI]"'
  for a in range(0,999999999):
    var = input("Input variable: ")
    val = input("Input value for variable: ")
    data += ',"'+var+'":"'+val+'"'
    print('Mau memasukkan data lagi? (Y/n) ')
    loop = input("[?] ")
    if loop == "Y" or loop == "y":
      continue
    else:
      break
  postData(data)
  

if __name__ == '__main__':
  print(banner)
  main()
